"""Scoring tests.

Expected values in test_hand_checked_fixture are worked out by hand on paper,
not generated by calling score_answers(). See the comment above that fixture
for the tally.
"""

from apps.logic.scoring import Answer, score_answers

# fmt: off
HAND_CHECKED_FIXTURE = (
    [Answer("D", "C")] * 6
    + [Answer("I", "S")] * 6
    + [Answer("S", "D")] * 4
    + [Answer("C", "I")] * 4
    + [Answer("D", "S")] * 4
)
# fmt: on


def test_hand_checked_fixture():
    # By hand:
    #   most:  D=6+4=10, I=6,        S=4,         C=4
    #   least: D=4,      I=4,        S=6+4=10,    C=6
    #   diff:  D=10-4=6, I=6-4=2,    S=4-10=-6,   C=4-6=-2
    # top_styles = {D} (max diff, 6), bottom_styles = {S} (min diff, -6)
    assert len(HAND_CHECKED_FIXTURE) == 24

    score = score_answers(HAND_CHECKED_FIXTURE)

    assert score.most == {"D": 10, "I": 6, "S": 4, "C": 4}
    assert score.least == {"D": 4, "I": 4, "S": 10, "C": 6}
    assert score.diff == {"D": 6, "I": 2, "S": -6, "C": -2}
    assert score.top_styles == {"D"}
    assert score.bottom_styles == {"S"}


def test_most_and_least_each_sum_to_total_answers():
    score = score_answers(HAND_CHECKED_FIXTURE)
    assert sum(score.most.values()) == 24
    assert sum(score.least.values()) == 24


def test_diff_values_always_sum_to_zero():
    # Property test: for any valid set of answers, the four diff values
    # cancel out, since most and least each independently sum to 24 across
    # the four styles.
    import random

    styles = ["D", "I", "S", "C"]
    rng = random.Random(0)

    for _ in range(50):
        answers = [Answer(*rng.sample(styles, 2)) for _ in range(24)]
        score = score_answers(answers)
        assert sum(score.diff.values()) == 0


def test_all_four_styles_tied():
    # Each style picked most exactly 6 times and least exactly 6 times,
    # arranged so every style's most-count equals its least-count.
    answers = (
        [Answer("D", "I")] * 6
        + [Answer("I", "D")] * 6
        + [Answer("S", "C")] * 6
        + [Answer("C", "S")] * 6
    )
    assert len(answers) == 24

    score = score_answers(answers)

    assert score.most == {"D": 6, "I": 6, "S": 6, "C": 6}
    assert score.least == {"D": 6, "I": 6, "S": 6, "C": 6}
    assert score.diff == {"D": 0, "I": 0, "S": 0, "C": 0}
    assert score.top_styles == {"D", "I", "S", "C"}
    assert score.bottom_styles == {"D", "I", "S", "C"}


def test_two_way_tie_at_the_top_and_bottom():
    # By hand:
    #   most:  D=8, I=8, S=4, C=4
    #   least: D=4, I=4, S=8, C=8
    #   diff:  D=4, I=4, S=-4, C=-4
    # D and I tied for the highest diff (+4); S and C tied for the lowest (-4).
    answers = (
        [Answer("D", "S")] * 8
        + [Answer("I", "C")] * 8
        + [Answer("S", "D")] * 4
        + [Answer("C", "I")] * 4
    )
    assert len(answers) == 24

    score = score_answers(answers)

    assert score.diff == {"D": 4, "I": 4, "S": -4, "C": -4}
    assert score.top_styles == {"D", "I"}
    assert score.bottom_styles == {"S", "C"}
